[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test

markers =
 ui: Запускает все UI автотесты
 smoke: Быстрые основные проверки
 regression: Регрессионные тесты
 slow: Медленные тесты
 critical: Критичные тесты
 registration: Тесты связанные с регистрацией
 authorization: Авторизация